-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.NAME
FROM ANIMAL_INS i JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE o.DATETIME IS NOT NULL
ORDER BY TIMESTAMPDIFF(DAY, i.DATETIME, o.DATETIME) DESC
LIMIT 2

-- 보호 기간이 가장 길었다 -> DATEDIFF(DAY, 보호 시작일, 입양일)