SELECT 
    cc.CAR_ID,
    cc.CAR_TYPE,
    ROUND(cc.DAILY_FEE * (1 - cd.DISCOUNT_RATE / 100) * 30) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR cc
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN cd
    ON cc.CAR_TYPE = cd.CAR_TYPE
WHERE 
    cc.CAR_TYPE IN ('세단', 'SUV')
    AND cd.DURATION_TYPE = '30일 이상'
    AND cc.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (
            END_DATE < '2022-11-01' OR START_DATE > '2022-11-30'
        )
    )
    AND ROUND(cc.DAILY_FEE * (1 - cd.DISCOUNT_RATE / 100) * 30) >= 500000
    AND ROUND(cc.DAILY_FEE * (1 - cd.DISCOUNT_RATE / 100) * 30) < 2000000
ORDER BY 
    FEE DESC, CAR_ID DESC