-- FOOD_PRODUCT: 식품 정보
-- FOOD_ORDER: 식품 주문 정보

-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회

Select fp.PRODUCT_ID, fp.PRODUCT_NAME, (fp.PRICE * sum(fo.AMOUNT)) as 'TOTAL_SALES'
FROM FOOD_PRODUCT fp left join FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE DATE_FORMAT(fo.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY fp.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC