WITH CAR_RENTAL_COUNT AS (
    SELECT 
        CAR_ID, 
        COUNT(*) AS TOTAL_RENTALS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING TOTAL_RENTALS >= 5
)

SELECT 
    MONTH(START_DATE) AS MONTH, 
    h.CAR_ID, 
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COUNT c ON h.CAR_ID = c.CAR_ID
WHERE 
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), h.CAR_ID
ORDER BY MONTH ASC, h.CAR_ID DESC;